# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\nfia_status\"\x18\n\x08\x46IAQuery\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x1b\n\x0b\x46IAResponse\x12\x0c\n\x04json\x18\x01 \x01(\t2\xd3\x01\n\x10\x46iaStatusService\x12=\n\x0cGetFiaStatus\x12\x14.fia_status.FIAQuery\x1a\x17.fia_status.FIAResponse\x12>\n\rPostFiaStatus\x12\x14.fia_status.FIAQuery\x1a\x17.fia_status.FIAResponse\x12@\n\x0fUpdateFiaStatus\x12\x14.fia_status.FIAQuery\x1a\x17.fia_status.FIAResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FIAQUERY']._serialized_start=26
  _globals['_FIAQUERY']._serialized_end=50
  _globals['_FIARESPONSE']._serialized_start=52
  _globals['_FIARESPONSE']._serialized_end=79
  _globals['_FIASTATUSSERVICE']._serialized_start=82
  _globals['_FIASTATUSSERVICE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
